from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Literal, Optional

class SignupRequest(BaseModel):
    email: str
    password: str
    username: str

class UserDict(BaseModel):
    id: str
    username: str
    email: str
    created_at: datetime
    updated_at: datetime

class LoginRequest(BaseModel):
    email: str
    password: str

class AuthResponse(BaseModel):
    user: UserDict
    access_token: str
    refresh_token: str
    token_type: str = "bearer"


# ---------------------------------------------------------------------------
# Interviews
# ---------------------------------------------------------------------------
InterviewType = Literal["job", "skill"]
Visibility = Literal["public", "private"]
QuestionType = Literal["text", "mcq"]

MAX_QUESTIONS = 5
MAX_ATTEMPTS_PER_USER = 10


class InterviewQuestion(BaseModel):
    question_id: str
    text: str
    order: int = Field(..., ge=0, le=MAX_QUESTIONS - 1)
    type: QuestionType = "text"


class CreateInterviewRequest(BaseModel):
    title: str
    description: str = ""
    type: InterviewType
    role: Optional[str] = None
    skill: Optional[str] = None
    visibility: Visibility = "public"
    # Optional: client may supply its own questions. If omitted, they are
    # generated by the AI. Capped at MAX_QUESTIONS.
    questions: Optional[List[InterviewQuestion]] = None


class InterviewDict(BaseModel):
    id: str
    user_id: str
    title: str
    description: str = ""
    type: InterviewType
    role: Optional[str] = None
    skill: Optional[str] = None
    visibility: Visibility = "public"
    questions: List[InterviewQuestion] = []
    attempt_count: int = 0
    created_at: datetime
    updated_at: datetime


# ---------------------------------------------------------------------------
# Attempts
# ---------------------------------------------------------------------------
AttemptStatus = Literal["not_started", "in_progress", "completed"]


class AttemptDict(BaseModel):
    id: str
    user_id: str
    interview_id: str
    status: AttemptStatus = "not_started"
    current_q_index: int = 0
    score: Optional[float] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime


# ---------------------------------------------------------------------------
# Answers (subcollection of attempts)
# ---------------------------------------------------------------------------
class SubmitAnswerRequest(BaseModel):
    question_id: str
    answer: str


class AnswerDict(BaseModel):
    id: str
    question_id: str
    answer: str
    score: Optional[float] = None
    feedback: str = ""
    user_id: str
    attempt_id: str
    interview_id: str
    created_at: datetime
    updated_at: datetime


class AttemptWithAnswersDict(AttemptDict):
    answers: List[AnswerDict] = []


# ---------------------------------------------------------------------------
# Report (subcollection of attempts, single doc "summary")
# ---------------------------------------------------------------------------
class ReportDict(BaseModel):
    id: str
    report: str = ""
    summary: str = ""
    strengths: List[str] = []
    improvements: List[str] = []
    score: Optional[float] = None
    user_id: str
    attempt_id: str
    interview_id: str
    created_at: datetime
    updated_at: datetime

