from datetime import datetime, timezone

from app.src.utils._auth.initialize import db
from app.src.utils._ai.interview_ai import generate_questions
from app.src.dict import (
    CreateInterviewRequest,
    InterviewDict,
    InterviewQuestion,
    MAX_QUESTIONS,
)


def create_interview(req: CreateInterviewRequest, user_id: str) -> InterviewDict:
    """Create an interview owned by ``user_id``.

    Questions are taken from the request when provided (capped at
    MAX_QUESTIONS and re-ordered), otherwise generated by the AI.
    """
    try:
        if req.type == "job" and not req.role:
            raise ValueError("role is required when type is 'job'")
        if req.type == "skill" and not req.skill:
            raise ValueError("skill is required when type is 'skill'")

        # Normalize questions: keep at most MAX_QUESTIONS and enforce 0-based order.
        if req.questions:
            questions = [
                InterviewQuestion(
                    question_id=q.question_id,
                    text=q.text,
                    order=order,
                    type=q.type,
                )
                for order, q in enumerate(req.questions[:MAX_QUESTIONS])
            ]
        else:
            questions = generate_questions(
                interview_type=req.type,
                title=req.title,
                description=req.description,
                role=req.role,
                skill=req.skill,
                count=MAX_QUESTIONS,
            )

        now = datetime.now(timezone.utc)
        interview_ref = db.collection("interviews").document()
        interview = InterviewDict(
            id=interview_ref.id,
            user_id=user_id,
            title=req.title,
            description=req.description,
            type=req.type,
            role=req.role if req.type == "job" else None,
            skill=req.skill if req.type == "skill" else None,
            visibility=req.visibility,
            questions=questions,
            attempt_count=0,
            created_at=now,
            updated_at=now,
        )

        interview_ref.set(interview.model_dump())
        return interview
    except ValueError as e:
        raise e
    except Exception as e:
        raise ValueError(f"Interview creation failed: {str(e)}")
